Add SDL3 to CI and upload build artifacts
FNA-XNA/FAudio pull request #359
Opened 2024-10-16 18:55 UTC by thatcosmonaut

It would be nice to figure out how to spit out a universal dylib for MacOS, but I'm not familiar enough with how that works. It would also be nice to figure out how to upload the release artifacts to the release page automatically when a release is tagged, but I'm not sure how to test that.

2024-10-17 01:46 UTC, flibitijibibo commented
In addition to macOS we also need a Rocky 8 VM for Linux builds - we should ask Misa about this.

2024-10-17 02:23 UTC, thatcosmonaut commented
Something like this? https://www.claudiokuenzler.com/blog/1381/how-to-run-github-ci-cd-workflows-actions-rocky-linux

2024-10-17 13:15 UTC, flibitijibibo commented
Oh, that looks a lot easier than what I remember... yeah, if that works with 8 then we can integrate that and the output binaries should be good to go.

2024-10-17 13:52 UTC, flibitijibibo requested changes
Output looks okay, so the final checklist:

- [x] MinGW (see comment)
- [x] Rocky Linux 8 x86_64
- [ ] Rocky Linux 8 aarch64

2024-10-17 13:52 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +  linux-mingw:
Do we want to replace the Windows MinGW build with this? The only difference should be the host OS, so let's use whichever one is faster and drop the other.

2024-10-17 20:57 UTC, thatcosmonaut commented
https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

>  We expect to begin offering Arm runners for open source projects by the end of the year.

Once this is enabled we can do the aarch builds. Working on the other stuff now.

2024-10-17 23:40 UTC, flibitijibibo reviewed
For MinGW, do the Rocky tools include `mingw32-cmake` and `mingw64-cmake`? That'll help eliminate the toolchain files if so.

2024-10-18 00:22 UTC, flibitijibibo requested changes
A few fixes here and there for the Rocky config - if this all works then the toolchain files can be deleted. We should also `chrpath -d` the Linux binaries, and possibly `strip -S` as well (not sure why this changes the Release binaries, but it does...)

2024-10-18 00:22 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +        cmake -B release -G Ninja . -DCMAKE_BUILD_TYPE=Release
We can trim down the build time with debug mode I bet

2024-10-18 00:22 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +        run: cmake -B release-x86 -G Ninja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=.github/mingw-w64-i686.cmake -DSDL2_LIBRARIES=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/i686-w64-mingw32/bi
I _think_ this still works...

```suggestion
        run: mingw32-cmake -B release-x86 -G Ninja . -DCMAKE_BUILD_TYPE=Release  -DSDL2_LIBRARIES=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/i686-w64-mingw32/bin/SDL2.dll -DSDL2_INCLUDE_DIRS=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/i686-w64-mingw32/include/SDL2
```

2024-10-18 00:22 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +        run: cmake -B release-x64 -G Ninja . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=.github/mingw-w64-x86_64.cmake -DSDL2_LIBRARIES=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/x86_64-w64-mingw3
Ditto:

```suggestion
        run: mingw64-cmake -B release-x64 -G Ninja . -DCMAKE_BUILD_TYPE=Release -DSDL2_LIBRARIES=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/x86_64-w64-mingw32/bin/SDL2.dll -DSDL2_INCLUDE_DIRS=${GITHUB_WORKSPACE}/SDL2-$SDL2_VERSION/x86_64-w64-mingw32/include/SDL2
```

2024-10-18 00:22 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +            opencl-headers openssl-devel patch perl-IPC-Cmd svn unix2dos xz zlib-static
Cleaning up my own mess:

```suggestion
        dnf install -y chrpath cmake gcc-c++ git ninja-build
```

2024-10-18 00:22 UTC, flibitijibibo commented on .github/workflows/ci.yml
> +            opencl-headers openssl-devel patch perl-IPC-Cmd svn unix2dos xz zlib-static
Ditto:

```suggestion
        dnf install -y chrpath cmake gcc-c++ git ninja-build
```

2024-10-18 02:01 UTC, thatcosmonaut commented
Rocky builds should be good now, it would be nice to spit out a universal MacOS dylib but I'm not gonna have time to work on that until next week at least.

2024-10-18 02:40 UTC, flibitijibibo approved these changes
Latest should be good as long as macOS cooperates...

2024-10-18 02:51 UTC, merged